
build: WinnipegCityData.class

WinnipegCityData.class: WinnipegCityData.java
	javac WinnipegCityData.java

run: WinnipegCityData.class
	java -cp .:mssql-jdbc-11.2.0.jre11.jar WinnipegCityData

clean:
	rm WinnipegCityData.class


