.PHONY : build


generateInsertFromCSV.class: generateInsertFromCSV.java 
	javac generateInsertFromCSV.java

build: generateInsertFromCSV.class 

run: build
	java  generateInsertFromCSV


	